"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { ModuleFailure, ModuleLoading } from "@/components/module-state";
import { WorkspaceShell } from "@/components/workspace-shell";
import { apiRequest } from "@/lib/api";
import { LoadState } from "@/lib/types";
type Pilot = { status: string; engagement: null | { started_at: string; ends_at: string; cohort_code: string }; checkpoints: { id: string; day_number: number; due_at: string; status: string; evidence: Record<string, unknown> }[]; metrics: Record<string, number> };
export default function PilotPage() {
  const [state, setState] = useState<LoadState<Pilot>>({ status: "loading" }); const [message, setMessage] = useState("");
  const load = useCallback(async () => { try { setState({ status: "ready", data: await apiRequest<Pilot>("/api/v1/pilot") }); } catch (error) { setState({ status: "error", message: error instanceof Error ? error.message : "Pilot progress could not be loaded." }); } }, []); useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function start(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await apiRequest("/api/v1/pilot/start", { method: "POST", body: JSON.stringify({ cohort_code: form.get("cohort") }) }); setMessage("Your 21-day guided pilot is active."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "The pilot could not be started."); } }
  return <WorkspaceShell><section className="content-page"><div className="page-heading"><div><p className="eyebrow">21-day evidence-led evaluation</p><h1>Guided Pilot</h1><p>Track usage, decision value, objections, and conversion evidence at days 7, 14, and 21.</p></div></div>{state.status === "loading" && <ModuleLoading />}{state.status === "error" && <ModuleFailure message={state.message} retry={() => void load()} />}{state.status === "ready" && state.data.status === "NOT_STARTED" && <form className="panel pilot-start" onSubmit={start}><h2>Start this workspace pilot</h2><label><span>Cohort code</span><input defaultValue="pilot-2026-01" minLength={2} name="cohort" required /></label><button className="primary-button" type="submit">Start 21-day pilot</button>{message && <p className="form-message">{message}</p>}</form>}{state.status === "ready" && state.data.engagement && <><section className="company-summary"><div><small>Status</small><strong>{state.data.status}</strong></div><div><small>Started</small><strong>{new Date(state.data.engagement.started_at).toLocaleDateString()}</strong></div><div><small>Ends</small><strong>{new Date(state.data.engagement.ends_at).toLocaleDateString()}</strong></div></section><section className="checkpoint-grid">{state.data.checkpoints.map((item) => <article key={item.id}><span className="eyebrow">Day {item.day_number}</span><h2>{item.day_number === 7 ? "Usage + relevance" : item.day_number === 14 ? "Brief quality + value" : "Conversion + pricing"}</h2><p>Due {new Date(item.due_at).toLocaleDateString()}</p><strong>{item.status}</strong></article>)}</section><section className="panel"><h2>Pilot evidence captured</h2><div className="metric-row">{Object.entries(state.data.metrics).map(([key, value]) => <div key={key}><strong>{value}</strong><span>{key.replaceAll("_", " ")}</span></div>)}</div></section></>}</section></WorkspaceShell>;
}
