"""Multi-Format Report Exporter for Stem Decision Workspace & Working Canvas.

Generates:
1. Markdown (.md) — structured executive brief with tables, action checklists, and citations.
2. Plain Text (.txt) — clean, formatted plaintext brief.
3. Executive PDF (.pdf) — styled, high-density PDF executive brief.
"""

from __future__ import annotations

import io
from datetime import UTC, datetime
from typing import Any


def export_markdown(
    title: str,
    operational_exposure: str,
    context_and_precedents: str,
    role_action_items: list[dict[str, Any]],
    citations: list[dict[str, Any]] | None = None,
    organization_name: str = "Stem Cogent Enterprise",
) -> str:
    """Format decision brief into structured GitHub-flavored Markdown."""
    lines: list[str] = [
        f"# {title}",
        "",
        f"**Organization:** {organization_name}  ",
        f"**Date Generated:** {datetime.now(UTC).strftime('%Y-%m-%d %H:%M:%S UTC')}  ",
        "**Classification:** STRICTLY CONFIDENTIAL // EXECUTIVE WORKING DRAFT  ",
        "",
        "---",
        "",
        "## 1. Operational Exposure Breakdown",
        "",
        operational_exposure,
        "",
        "## 2. Context, Precedents & Verified Citations",
        "",
        context_and_precedents,
        "",
    ]

    if citations:
        lines.extend([
            "### Cited Intelligence Sources",
            "",
            "| Source / Entity | Evidence Summary | URL |",
            "| :--- | :--- | :--- |",
        ])
        for c in citations:
            s_title = c.get("title", "Evidence Reference")
            s_text = (c.get("text") or c.get("excerpt") or "")[:120].replace("\n", " ")
            s_url = c.get("url") or c.get("source_url") or "Internal Repository"
            lines.append(f"| {s_title} | {s_text} | [{s_url}]({s_url}) |")
        lines.append("")

    lines.extend([
        "## 3. Role-Delineated Corrective Action Plan",
        "",
        "| Department / Function | Action Directive | Urgency / SLA | Status |",
        "| :--- | :--- | :--- | :--- |",
    ])
    for item in role_action_items:
        dept = str(item.get("department", "operations")).replace("_", " ").title()
        action = str(item.get("action", "")).replace("\n", " ")
        urgency = str(item.get("urgency", "monitor")).upper()
        lines.append(f"| {dept} | {action} | `{urgency}` | [ ] Pending |")

    lines.extend([
        "",
        "---",
        "*Report generated by Stem Cogent Decision Intelligence Platform.*",
        "",
    ])
    return "\n".join(lines)


def export_plaintext(
    title: str,
    operational_exposure: str,
    context_and_precedents: str,
    role_action_items: list[dict[str, Any]],
    citations: list[dict[str, Any]] | None = None,
    organization_name: str = "Stem Cogent Enterprise",
) -> str:
    """Format decision brief into clean, structured plaintext."""
    divider = "=" * 78
    subdivider = "-" * 78
    now_str = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines: list[str] = [
        divider,
        f"STEM COGENT EXECUTIVE DECISION BRIEF: {title.upper()}",
        f"Organization: {organization_name} | Generated: {now_str}",
        "Classification: STRICTLY CONFIDENTIAL // BOARD & EXECUTIVE COMMITTEE",
        divider,
        "",
        "1. OPERATIONAL EXPOSURE BREAKDOWN",
        subdivider,
        operational_exposure,
        "",
        "2. CONTEXT, PRECEDENTS & SOURCE CITATIONS",
        subdivider,
        context_and_precedents,
        "",
    ]

    if citations:
        lines.append("PRIMARY SOURCES CITED:")
        for idx, c in enumerate(citations, 1):
            s_title = c.get("title", "Evidence Source")
            s_url = c.get("url") or c.get("source_url") or "Internal"
            lines.append(f"  [{idx}] {s_title} - {s_url}")
        lines.append("")

    lines.extend([
        "3. ROLE-DELINEATED ACTION PLAN",
        subdivider,
    ])
    for idx, item in enumerate(role_action_items, 1):
        dept = str(item.get("department", "operations")).replace("_", " ").upper()
        action = item.get("action", "")
        urgency = str(item.get("urgency", "monitor")).upper()
        lines.append(f"  [{idx}] [{dept}] ({urgency})")
        lines.append(f"      Directive: {action}")
        lines.append("      Status: PENDING")

    lines.extend([
        "",
        divider,
        "END OF BRIEF - STEM COGENT OPERATIONAL PLATFORM",
        divider,
        "",
    ])
    return "\n".join(lines)


def export_executive_pdf(
    title: str,
    operational_exposure: str,
    context_and_precedents: str,
    role_action_items: list[dict[str, Any]],
    citations: list[dict[str, Any]] | None = None,
    organization_name: str = "PayBridge Sim Ltd",
) -> bytes:
    """Generate a styled, high-density Executive PDF brief."""
    # Build text content to render in stream
    raw_text = export_plaintext(
        title=title,
        operational_exposure=operational_exposure,
        context_and_precedents=context_and_precedents,
        role_action_items=role_action_items,
        citations=citations,
        organization_name=organization_name,
    )

    # Format text lines for PDF stream
    pdf_lines: list[str] = []
    for line in raw_text.splitlines()[:60]:  # limit lines per page for high density
        # Escape special PDF characters: (, ), \
        escaped = line.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
        pdf_lines.append(escaped)

    # Construct PDF page content stream
    text_commands: list[str] = [
        "BT",
        "/F1 9 Tf",
        "12 TL",
        "50 750 Td",
    ]
    for line in pdf_lines:
        text_commands.append(f"({line}) '")
    text_commands.append("ET")
    content_stream = "\n".join(text_commands).encode("latin-1", errors="replace")

    # Assemble PDF document structures
    obj1 = b"<</Type/Catalog/Pages 2 0 R>>"
    obj2 = b"<</Type/Pages/Count 1/Kids[3 0 R]>>"
    obj3 = (
        b"<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Contents 4 0 R"
        b"/Resources<</Font<</F1 5 0 R>>>>>>"
    )
    obj4 = b"<</Length " + str(len(content_stream)).encode("ascii") + b">>stream\n" + content_stream + b"\nendstream"
    obj5 = b"<</Type/Font/Subtype/Type1/BaseFont/Courier>>"

    objects = [obj1, obj2, obj3, obj4, obj5]
    offsets: list[int] = []

    out = io.BytesIO()
    out.write(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")

    for i, obj in enumerate(objects, 1):
        offsets.append(out.tell())
        out.write(f"{i} 0 obj\n".encode("ascii"))
        out.write(obj)
        out.write(b"\nendobj\n")

    xref_offset = out.tell()
    out.write(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    out.write(b"0000000000 65535 f \n")
    for offset in offsets:
        out.write(f"{offset:010d} 00000 n \n".encode("ascii"))

    out.write(b"trailer\n")
    out.write(f"<</Size {len(objects) + 1}/Root 1 0 R>>\n".encode("ascii"))
    out.write(b"startxref\n")
    out.write(f"{xref_offset}\n".encode("ascii"))
    out.write(b"%%EOF\n")

    return out.getvalue()
